version: 0.2
phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y yarn
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn run build
  post_build:
    commands:
      - aws s3 sync --delete --exclude static/* build/ "s3://${BUCKET_NAME}"
      - aws s3 sync --delete --cache-control "max-age=0" build/static "s3://${BUCKET_NAME}/static"